apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: runner-test
  namespace: yuvro
spec:
  ingressClassName: nginx
  rules:
    - host: runner.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: runner-test
                port:
                  number: 3002
